services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bundle check || bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 8000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}

volumes:
  postgres_data:
  bundle_cache:
